wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2167549"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2167551"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2167656"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2167655"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2167654"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2167552"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2167550"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2167548"
