wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2162325"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2162327"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2162412"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2168396"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2168397"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2162326"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2162415"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2162414"
