wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2152861"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2152860"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2152922"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2152859"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2160917"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2152921"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2152923"
wget --continue --trust-server-names "https://go.microsoft.com/fwlink/?LinkID=2152862"
