---
BasedOnStyle: LLVM
AccessModifierOffset: -4
AlignEscapedNewlines: Left
AlignTrailingComments: false
AlwaysBreakTemplateDeclarations: Yes
BreakInheritanceList: BeforeComma
BreakConstructorInitializers: BeforeComma
ColumnLimit: 0
IndentWidth: 4
ObjCBlockIndentWidth: 4
ReflowComments: false
SortIncludes: false
SpaceBeforeCtorInitializerColon: false
SpaceBeforeInheritanceColon: false
SpacesInContainerLiterals: false
TabWidth: 4
...
