---
BasedOnStyle: LLVM
AccessModifierOffset: -4
AlignConsecutiveMacros: true
AlignEscapedNewlines: Left
AlignOperands: AlignAfterOperator
AllowAllArgumentsOnNextLine: false
AllowAllConstructorInitializersOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortFunctionsOnASingleLine: None
AllowShortLambdasOnASingleLine: None
AlwaysBreakTemplateDeclarations: Yes
BreakInheritanceList: BeforeComma
BreakConstructorInitializers: BeforeComma
ColumnLimit: 0
IndentWidth: 4
NamespaceIndentation: All
ObjCBlockIndentWidth: 4
ReflowComments: false
SortIncludes: false
SpaceBeforeCtorInitializerColon: false
SpaceBeforeInheritanceColon: false
SpacesInContainerLiterals: false
TabWidth: 4
...
