name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install
        shell: bash
        run: |
          sudo apt-get install -f -q -qq -y \
          build-essential \
          python3-dev \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          python3-cffi \
          libcairo2 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libgdk-pixbuf2.0-0 \
          libffi-dev \
          shared-mime-info \
          fonts-wqy-microhei
          python3 -m pip install --quiet --upgrade pip
          python3 -m pip install --quiet --requirement requirement.txt

      - name: Build
        shell: bash
        env:
          ENABLE_PDF_EXPORT: 1
          output: build
        run: |
          python3 -m mkdocs build --quiet --site-dir $output
          for i in `ls -A`; do \
          if [ "$i" == ".git" ]; then continue; fi;\
          if [ "$i" == "$output" ]; then continue; fi;\
          rm -rf $i; done
          for i in `ls -A $output`; do \
          mv -t . $output/$i; done
          rmdir $output

      - name: Deploy
        shell: bash
        env:
          GPG_KEY: ${{ secrets.COMMIT_GPG_KEY }}
          GPG_ID: ${{ secrets.COMMIT_GPG_ID }}
          branch: gh-pages
        run: |
          git config user.name       "github-actions[bot]"
          git config user.email      "59302530+tqfx@users.noreply.github.com"
          git config user.signingkey $GPG_ID
          git config commit.gpgsign  true
          git config core.autocrlf   input
          git config core.quotepath  false
          git config core.filemode   false
          git config core.ignorecase false
          git config --list
          git checkout --quiet --orphan $branch
          git add --all
          echo "$GPG_KEY" > $GPG_ID && gpg --import $GPG_ID && rm $GPG_ID
          git commit --quiet --signoff --message $(git rev-parse origin/master)
          git push --force origin $branch
