name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Setup
        shell: bash
        run: |
          git clone https://github.com/tqfx/scripts.git gh-scripts
          bash gh-scripts/pip-mkdocs.sh requirements.txt

      - name: Build
        shell: bash
        env:
          ENABLE_PDF_EXPORT: 1
          OUTPUT: build
        run: |
          python3 -m mkdocs build --quiet --site-dir $OUTPUT

      - name: Deploy
        shell: bash
        env:
          COMMIT_GPG_KEY: ${{ secrets.COMMIT_GPG_KEY }}
          COMMIT_GPG_ID: ${{ secrets.COMMIT_GPG_ID }}
          BRANCH: gh-pages
        run: |
          bash gh-scripts/gh-config.sh
          bash gh-scripts/gh-deploy.sh build LICENSE
