name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Setup
        shell: bash
        run: |
          sudo apt-get install -f -q -qq -y \
          build-essential \
          python3-dev \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          python3-cffi \
          libcairo2 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libgdk-pixbuf2.0-0 \
          libffi-dev \
          shared-mime-info \
          fonts-wqy-microhei
          python3 -m pip install --quiet --upgrade pip
          python3 -m pip install --quiet --requirement requirements.txt

      - name: Build
        shell: bash
        env:
          ENABLE_PDF_EXPORT: 1
          OUTPUT: build
        run: |
          python3 -m mkdocs build --quiet --site-dir $OUTPUT

      - name: Deploy
        shell: bash
        env:
          COMMIT_GPG_KEY: ${{ secrets.COMMIT_GPG_KEY }}
          COMMIT_GPG_ID: ${{ secrets.COMMIT_GPG_ID }}
          BRANCH: gh-pages
        run: |
          bash scripts/gh-config.sh
          bash scripts/gh-deploy.sh build LICENSE
