name: gh-pages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          sudo apt-get install -f -q -qq -y build-essential \
          python3-dev python3-pip python3-setuptools python3-wheel python3-cffi \
          libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev \
          shared-mime-info fonts-wqy-microhei
          python3 -m pip install --quiet --upgrade pip
          python3 -m pip install --quiet --requirement requirements.txt
          python3 -m mkdocs build --quiet --site-dir build
        env:
          ENABLE_PDF_EXPORT: 1
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
          disable_nojekyll: true
          publish_branch: gh-pages
          force_orphan: true
          publish_dir: build
